### PR TITLE
Fix Safari ctrl+click context menu

### LINKED ISSUE #287: Context menu doesn't work on Safari, secondary issue on Chrome/Ff
- [x] Control-click shows the context menu briefly, but it immediately disappears; holding the "mouse" down does keep the menu visible, but the action doesn't work at all. Fixed in #290.
- [ ] If you hold/drag the "mouse" after control-click, choosing an item doesn't work without an additional click. Fixed in #802.

### PR DESCRIPTION
**Pull request by nedkamburov**
Fixes #287

### CODE REVIEW

File: src/fontra/views/editor/editor.js [hunk 1]
```diff
@@ -188,6 +188,7 @@ export class EditorController {
     this.canvasController.canvas.addEventListener("contextmenu", (event) =>
       this.contextMenuHandler(event)
     );
+
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:191]: Can you undo this redundant change, and the one near line 962?

File: src/fontra/views/editor/editor.js [hunk 2]
```diff
@@ -958,6 +958,7 @@ export class EditorController {
         return;
       }
     }
+
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:961]:
```suggestion
```
