### PR TITLE
Fix context-menu close #2068

### LINKED ISSUE #2068: Context menu doesn't go away
Scenario, in the editor:
- control- or right-click anywhere to get the context menu
- click anywhere outside the context menu should make it go away, but it doesn't

This is a regression caused by d86f79db04f1783fb7804ecfe8ea143b63c5110d. @giovanniTramonto can you help?

### PR DESCRIPTION
**Pull request by giovanniTramonto**
Fixes #2068

### CODE REVIEW

File: src-js/fontra-webcomponents/src/menu-bar.js [hunk 1]
```diff
@@ -145,6 +145,7 @@ export class MenuBar extends SimpleElement {
     };
     const menuPanel = new MenuPanel(items, {
       position,
+      context: "menu-bar",
```
Comment (justvanrossum) [inline src-js/fontra-webcomponents/src/menu-bar.js:148]: I'm just wondering, we didn't need this before, why do we need it now?

**Comment by justvanrossum** [comment]
This doesn't fix everything: repeated *control*-click still give multiple context menus.

**Comment by justvanrossum** [comment]
Would it be better to revert #2060 first, and do a fresh attempt?

File: src-js/fontra-webcomponents/src/menu-bar.js (hunk 1 above)
Comment (giovanniTramonto) [reply src-js/fontra-webcomponents/src/menu-bar.js:142]: It’s easier to figure out if target is in `menu-bar`, when testing if the panel should close. The `mousedown` event in panel fires at last and would close the panel immediately after opening, when hitting menu-item. Before this was done on `click`. Now all happens in `mousedown`.
I tried to avoid by using click for the closing. But it did not change much, actually. And in OS menu all is done with `mousedown`. So now works with `mousedown` too.

**Comment by giovanniTramonto** [comment]
> This doesn't fix everything: repeated _control_-click still give multiple context menus.

Should work now

**Comment by giovanniTramonto** [comment]
> Would it be better to revert #2060 first, and do a fresh attempt?

Sure. Feel free to revert

**Comment by justvanrossum** [comment]
Thanks, I can confirm it works. I'll merge.

(Would be nice to use dispatchCustomEvent() in other places, too.)
