### PR TITLE
Safari copy/paste plain text to the clipboard

### LINKED ISSUE #312: [clipboard] Implement custom clipboard to work around Safari and Firefox limitations
In Chrome, we can use custom clipboard types such as `"web fontra/static-glyph"`. This does not work in Safari, and raises an error on write in Firefox. Yet, if we *also* want to put SVG  or GLIF on the clipboard (which will have to be of type `text/plain`), we can't put our own format on the `text/plain` clipboard.

I think we should implement our own clipboard storage in LocalStorage, but we need to be clever as to when to invalidate it, as it needs to work seemlessly alongside the system clipboard.

Relates to #260 and #75.

### PR DESCRIPTION
**Pull request by nedkamburov**
Partially fixes #312

### CODE REVIEW

File: src/fontra/views/editor/editor.js [hunk 1]
```diff
@@ -692,25 +692,34 @@ export class EditorController {
     }
     this.basicContextMenuItems.push(MenuItemDivider);
 
+    const safariHTTPAgent =
+      navigator.userAgent.indexOf("Safari") > -1 &&
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:696]: In Chrome, the userAgent string also contains the substring "Safari".

File: src/fontra/views/editor/editor.js [hunk 2]
```diff
@@ -692,25 +692,34 @@ export class EditorController {
...
+      window.location.protocol === "http:";
+    if (safariHTTPAgent) this.initFallbackClipboardEventListeners();
+    if (!safariHTTPAgent) {
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:699]: This can be an else of the previous if.

File: src/fontra/views/editor/editor.js [hunk 3]
```diff
@@ -692,25 +692,34 @@ export class EditorController {
     }
     this.basicContextMenuItems.push(MenuItemDivider);
 
+    const safariHTTPAgent =
+      navigator.userAgent.indexOf("Safari") > -1 &&
+      window.location.protocol === "http:";
+    if (safariHTTPAgent) this.initFallbackClipboardEventListeners();
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:698]: Please make this a block with { and }.

File: src/fontra/views/editor/editor.js [hunk 4]
```diff
@@ -910,6 +934,16 @@ export class EditorController {
     await writeToClipboard(clipboardObject);
   }
 
+  _copyToEventClipboard(event) {
+    if (!event) return;
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:938]: I don't see how this method gets called with a falsy event. Perhaps this line is redundant?

File: src/fontra/views/editor/editor.js [hunk 5]
```diff
@@ -776,6 +785,30 @@ export class EditorController {
...
+        event.preventDefault();
+        this._copyToEventClipboard(event);
+      }
+    });
+
+    window.addEventListener("cut", (event) => {
+      if (document.activeElement === this.canvasController.canvas) {
+        event.preventDefault();
+        this._copyToEventClipboard(event);
+        this.doCut(event);
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:807]: Instead of passing the event, let's just pass a flag. I think the flag argument coud be called "writeToClipboard", which should be `true` by default, so we'd pass `false` here.

File: src/fontra/views/editor/editor.js [hunk 6]
```diff
@@ -858,7 +891,7 @@ export class EditorController {
     return !!this.sceneController.selection.size;
   }
 
-  async doCut() {
+  async doCut(event = null) {
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:894]:
```suggestion
  async doCut(writeToClipboard = true) {
```

File: src/fontra/views/editor/editor.js [hunk 7]
```diff
@@ -868,7 +901,7 @@ export class EditorController {
       this.sceneController.selection = new Set();
       return "Cut Selection";
     });
-    if (copyResult) {
+    if (copyResult && !event) {
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:904]:
```suggestion
    if (copyResult && writeToClipboard) {
```

**Review by justvanrossum — CHANGES_REQUESTED** [review]

File: src/fontra/views/editor/editor.js (hunk 1 above)
Comment (justvanrossum) [reply src/fontra/views/editor/editor.js:696]: https://stackoverflow.com/questions/7944460/detect-safari-browser has some useful answers. I like this one:
```js
var isSafari = navigator.vendor && navigator.vendor.indexOf('Apple') > -1 &&
               navigator.userAgent &&
               navigator.userAgent.indexOf('CriOS') == -1 &&
               navigator.userAgent.indexOf('FxiOS') == -1;
```

Comment (nedkamburov) [reply src/fontra/views/editor/editor.js:696]: Maybe a combo?
```
const isSafari =
      navigator.vendor &&
      navigator.vendor.indexOf("Apple") > -1 &&
      navigator.userAgent.indexOf("Safari") > -1 &&
      navigator.userAgent.indexOf("CriOS") == -1 &&
      navigator.userAgent.indexOf("FxiOS") == -1 &&
      window.safari !== undefined &&
      window.location.protocol === "http:";
```

Comment (justvanrossum) [reply src/fontra/views/editor/editor.js:696]: Seems a bit redundant. Maybe only `window.safari !== undefined` and the `http:` check? I understand the former is only for desktop, which is fine for us actually.

Comment (nedkamburov) [reply src/fontra/views/editor/editor.js:696]: Yes, the `vendor` and` userAgent.indexOf `are probably going to give us some false positives.
Going back to the simple stuff!

**Review by justvanrossum — APPROVED** [review]
