### PR TITLE
Various fixes related to sidebar resizing.

### LINKED ISSUE #590: [sidebars] Sidebar misc items, related to resizing
I have some followup feedback on #583:

- [ ] Toggling the sidebar doesn't animate anymore (the "animating" class)
- [ ] The "gutter" element to drag the sidebar width takes up space _in addition_ to the margin. The margin + gutter space should be the same as the "old" margin
- [ ] Sliders in sliders tab don't grow with sidebar

### PR DESCRIPTION
**Pull request by fatih-erikli**
This fixes #590.

- [x] Toggling the sidebar doesn't animate anymore (the "animating" class)
- [x] The "gutter" should not take additional space in sidebar
- [x] Sliders in settings tab should grow with sidebar
- [x] User select should be disabled on the root document when resizing

### CODE REVIEW

File: src/fontra/client/web-components/designspace-location.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ export class DesignspaceLocation extends UnlitElement {
   static styles = `
     :host {
       display: grid;
-      grid-template-columns: 25% auto;
+      grid-template-columns: max-content auto;
```
Comment (justvanrossum) [inline src/fontra/client/web-components/designspace-location.js:10]: Could you try fixing the slider resizing while keeping the first column at 25%? The reason it was 25% is to prevent very long axis names to squish away the sliders too much.

File: src/fontra/views/editor/editor.html [hunk 2]
```diff
@@ -32,6 +32,13 @@
       --sidebar-tab-width: 3em;
       --sidebar-content-width-left: 20em;
       --sidebar-content-width-right: 22em;
+      --resize-cursor: col-resize;
+    }
+
+    :root.--resize {
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.html:38]: What's the reason for this particular naming? Couldn't this class simply be called "resizing"?

File: src/fontra/views/editor/editor.html [hunk 3]
```diff
@@ -315,7 +317,12 @@
     .sidebar-resize-gutter {
       height: 100%;
       width: 8px;
-      cursor: col-resize;
+      cursor: var(--resize-cursor);
+      position: absolute;
+    }
+
+    .sidebar-container.left .sidebar-resize-gutter {
+      right: 0;
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.html:325]: Suggest to make this `-4px`, and add one for `.right.` as well: `left: -4px`.

This would center the gutter around the edge, instead of being completely inside the tab. I feel this is more natural beahvior.

I actually wonder if 8px width for the gutter isn't too generous. Perhaps 6 is enough?

Comment (justvanrossum) [reply src/fontra/views/editor/editor.html:325]: Or even 4px. It seems enough to grab it.

File: src/fontra/views/editor/editor.html [hunk 4]
```diff
@@ -316,13 +316,17 @@
...
       height: 100%;
-      width: 8px;
+      width: 6px;
       cursor: var(--resize-cursor);
       position: absolute;
     }
 
     .sidebar-container.left .sidebar-resize-gutter {
-      right: 0;
+      right: -4px;
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.html:325]: This should be half of the width. Same for right.

Did you try with a width of 4px? Did you find it too narrow?

Comment (fatih-erikli) [reply src/fontra/views/editor/editor.html]: Ok. I made it 4px with, -2px for offsets. Looks good to me.

File: src/fontra/views/editor/editor.js [hunk 5]
```diff
@@ -458,23 +458,25 @@ export class EditorController {
...
           width = initialWidth + (initialPointerCoordinateX - event.clientX);
-        } else if (growDirection === "right") {
+          cssProperty = "--sidebar-content-width-right";
+        } else {
           width = initialWidth + (event.clientX - initialPointerCoordinateX);
+          cssProperty = "--sidebar-content-width-left";
         }
         width = clamp(width, 200, 500);
-        sidebarResizing.style.width = `${width}px`;
+        document.querySelector(":root").style.setProperty(cssProperty, `${width}px`);
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.js:470]: Can we use `document.documentElement` instead of `document.querySelector(":root")`, or would that be a different element, or a less preferred style?

File: src/fontra/views/editor/editor.html [hunk 6]
```diff
@@ -32,6 +32,13 @@
       --sidebar-tab-width: 3em;
       --sidebar-content-width-left: 20em;
       --sidebar-content-width-right: 22em;
+      --resize-cursor: col-resize;
+    }
+
+    :root.resizing {
```
Comment (justvanrossum) [inline src/fontra/views/editor/editor.html:38]: Looking at it now I think this class should be called "sidebar-resizing", to make it more obvious what's goin on here. I also wonder if we can move this entire `:root` block closer to the sidebar CSS, for the same reason.

File: src/fontra/views/editor/editor.js (hunk 5 above)
Comment (fatih-erikli) [reply src/fontra/views/editor/editor.js:470]: We may move them to `#editor-container`. Is that what you mean?

Comment (justvanrossum) [reply src/fontra/views/editor/editor.js:470]: No, I literally meant to ask about `document.querySelector(":root")` vs. `document.documentElement`. Are they the same, and if yes, should we use the former instead?

Comment (fatih-erikli) [reply src/fontra/views/editor/editor.js:470]: Ok. I think it's ok, we can use documentElement. I will send a patch.

File: src/fontra/views/editor/editor.html (hunk 6 above)
Comment (fatih-erikli) [reply src/fontra/views/editor/editor.html:38]: I think class "sidebar-resizing" is ok, more explicit is the better. I will send a patch.

What do you mean by moving entire `:root` to the sidebar css?

Comment (fatih-erikli) [reply src/fontra/views/editor/editor.html:38]: Lowering by one block? There is only sidebar container between them.

Comment (justvanrossum) [reply src/fontra/views/editor/editor.html:38]: Ah yes, lowering by one block is good, thanks.

Comment (fatih-erikli) [reply src/fontra/views/editor/editor.html]: Sent a patch.

**Review by justvanrossum — APPROVED** [review]
